spring:
  application:
    name: cubanacan-api
  jpa:
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.jdbc.time_zone]": UTC

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
