spring:
  application:
    name: cubanacan-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotelflow}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:change-me}
  jpa:
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.jdbc.time_zone]": UTC

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
